#!/usr/bin/env bash

rm -rf /tmp/release
mkdir -p /tmp/release
cp glam-bin /tmp/release
VERSION=$(cat resources/glam/version)

cd /tmp/release

## release binary as zip archive

zip "glam-$VERSION-$GLAM_PLATFORM-amd64.zip" glam-bin

## cleanup

rm glam-bin
