#!/usr/bin/env bash

set -eo pipefail

mkdir -p classes
clojure -M -e "(compile 'glam.main)"

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set $GRAALVM_HOME"
    exit 1
fi

"$GRAALVM_HOME/bin/native-image" \
    -cp "$(clojure -Spath):classes" \
    -H:Name=glam-bin \
    -H:+ReportExceptionStackTraces \
    --initialize-at-build-time  \
    --report-unsupported-elements-at-runtime \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx3g" \
    glam.main
